apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: stock
        image: bingoladen/stock:v21
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: stock-secrets
              key: dbhost
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: stock-secrets
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: stock-secrets
              key: dbuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stock-secrets
              key: dbpassword
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: stock-secrets
              key: dbport
        ports:
        - containerPort: 6000
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  selector:
    app: stock
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 6000  # The port your application is listening on inside the pod
      nodePort: 30000  # The external port to be exposed
  